name: 'lotto-action'
description: 'GitHub Action for lotto purchase'
branding:
  icon: 'dollar-sign'
  color: 'yellow'
author: 'bang9<gusrn1423@naver.com>'
inputs:
  id:
    required: true
    description: 'Input dhlottery id'
    default: ''
  pwd:
    required: true
    description: 'Input dhlottery password'
    default: ''
  token:
    required: true
    description: 'Input github token'
    default: ''
  amount:
    required: false
    description: 'Input amount of lotto game(max: 5)'
    default: '5'
runs:
  using: 'node16'
  main: 'dist/index.js'
