name: 'lotto-archive-action'
description: 'GitHub Action for lotto archiving'
branding:
  icon: 'dollar-sign'
  color: 'yellow'
author: 'bang9<gusrn1423@naver.com>'
inputs:
  numbersArray:
    required: true
    description: '구매한 로또 번호의 배열 ("[[1,2,3,4,5,6],[1,2,3,4,5,6]]")'
    default: '[]'
  round:
    required: true
    description: '구매한 로또 번호의 회차'
    default: '0'
  token:
    required: true
    description: 'GitHub 토큰'
    default: ''
  debug:
    required: false
    description: 'Debug mode 활성화'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
