name: ci
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
env:
  CACHE_NODE_MODULES_PATH: |
    node_modules

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Get lockfile hash
        id: lockfile_hash
        run: echo "hash=${{ hashFiles('**/pnpm-lock.lock') }}" >> $GITHUB_OUTPUT

      - name: Check cached node_modules
        id: check_cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ steps.lockfile_hash.outputs.hash }}

      - name: Install dependencies
        if: steps.check_cache.outputs.cache-hit == ''
        run: pnpm install --frozen-lockfile
    outputs:
      cache_node_modules_key: ${{ steps.lockfile_hash.outputs.hash }}

  run-lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Check cached node_modules
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ needs.prepare.outputs.cache_node_modules_key }}

      - name: Run lint
        run: pnpm lint

  run-build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Check cached node_modules
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ needs.prepare.outputs.cache_node_modules_key }}

      - name: Run build
        run: pnpm build
#  run-test:
#    needs: prepare
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Enable corepack
#        run: corepack enable
#      - name: Use Node.js 23
#        uses: actions/setup-node@v4
#        with:
#          node-version: 23
#
#      - name: Check cached node_modules
#        uses: actions/cache@v4
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: ${{ needs.prepare.outputs.cache_node_modules_key }}
#
#      - name: Run test
#        env:
#          LOTTO_ID: ${{ secrets.lotto_id }}
#          LOTTO_PWD: ${{ secrets.lotto_pwd }}
#          LOTTO_COOKIE: ${{ secrets.lotto_cookie }}
#        run: pnpm test --verbose --collect-coverage
#
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          verbose: true
